# 🚀 **Introduction to NumPy:**  
*A Beginner-Friendly Jupyter Notebook*  

**Created by [ Ahmad | The Analyst ]**  

---

## 📚 **Table of Contents**  
1. [Why NumPy? �](#why-numpy)  
   - Speed ⚡  
   - Memory Efficiency 💾  
   - Vectorized Operations 🔄  
2. [NumPy vs. Python Lists ⚔️](#numpy-vs-python-lists)  
3. [Installing & Importing NumPy 📥](#installing--importing-numpy)  
4. [Quick Quiz ❓](#quick-quiz)  
5. [Mini-Project: Analyzing Temperature Data 🌡️](#mini-project)  
6. [Pro Tips & Common Pitfalls 💡](#pro-tips)  

---

<a id="why-numpy"></a>  
## 1️⃣ **Why NumPy? 🧠**  

NumPy (**Num**erical **Py**thon) is a powerful library for numerical computing in Python. But why should you care?  

### ⚡ **Speed**  
NumPy is **way faster** than Python lists because:  
- It’s written in **C** (super fast low-level language).  
- It uses **fixed-type arrays** (no type-checking overhead).  

**Example:**

In [1]:
import numpy as np
import time

# Using Python lists
python_list = list(range(1, 1000000))
start_time = time.time()
squared_list = [x ** 2 for x in python_list]
print(f"Python list took: {time.time() - start_time:.5f} seconds")

# Using NumPy
numpy_array = np.arange(1, 1000000)
start_time = time.time()
squared_array = numpy_array ** 2
print(f"NumPy took: {time.time() - start_time:.5f} seconds")

Python list took: 0.07604 seconds
NumPy took: 0.00452 seconds


> **👉 NumPy is ~20x faster!** 

### 💾 **Memory Efficiency**  
NumPy stores data **more compactly** than Python lists.  


In [3]:
import sys

python_list = list(range(1000))
numpy_array = np.arange(1000)

print(f"Python list size: {sys.getsizeof(python_list)} bytes")  
print(f"NumPy array size: {sys.getsizeof(numpy_array)} bytes") 

Python list size: 8056 bytes
NumPy array size: 8112 bytes


*Wait, why is NumPy bigger here?* 🤔  
**Because:** For small arrays, NumPy has some overhead. But for **large datasets**, NumPy wins!  

### 🔄 **Vectorized Operations**  
No more writing loops! NumPy lets you apply operations **element-wise**.  


In [4]:
# Without NumPy (using loops)
a = [1, 2, 3]
b = [4, 5, 6]
result = [a[i] + b[i] for i in range(len(a))]

# With NumPy (vectorized)
a_np = np.array([1, 2, 3])
b_np = np.array([4, 5, 6])
result_np = a_np + b_np

print("Python list addition:", result)  
print("NumPy addition:", result_np)  

Python list addition: [5, 7, 9]
NumPy addition: [5 7 9]


**👉 Cleaner, faster, and no loops!**  

---

<a id="numpy-vs-python-lists"></a>  
## 2️⃣ **NumPy vs. Python Lists ⚔️**  

| Feature          | Python Lists | NumPy Arrays |
|------------------|-------------|-------------|
| **Speed**        | Slow (dynamic typing) | Fast (fixed type) |
| **Memory**       | Higher overhead | Optimized storage |
| **Functionality** | Basic operations | Advanced math (sin, log, etc.) |
| **Flexibility**  | Mixed data types | Homogeneous data |

**Example:**  

In [5]:
mixed_list = [1, "hello", 3.14]  # ✅ Works  
numpy_array = np.array([1, "hello", 3.14])  # ❌ Converts all to strings!  
print(numpy_array)

['1' 'hello' '3.14']


**⚠️ Pitfall:** NumPy arrays **must** have the same data type!  

---

<a id="installing--importing-numpy"></a>  
## 3️⃣ **Installing & Importing NumPy 📥**  

### **Installation**  
Run in your terminal:  
```bash
pip install numpy
```

### **Importing**  
```python
import numpy as np  # Standard convention!
```

**Check version:**  
```python
print(np.__version__)  # Should output something like '1.21.0'
```

---

<a id="quick-quiz"></a>  
## ❓ **Quick Quiz**  

1. **Why is NumPy faster than Python lists?**  
   - A) Because it’s written in Python  
   - B) Because it uses C under the hood ✅  
   - C) Because it has more functions  

2. **What happens if you mix data types in a NumPy array?**  
   - A) It raises an error  
   - B) It converts all elements to the same type ✅  
   - C) It works fine  

---

<a id="mini-project"></a>  
## 🎯 **Mini-Project: Analyzing Temperature Data 🌡️**  

**Scenario:** You have daily temperatures (in °C) for a week.  

**Tasks:**  
1. Convert temperatures to Fahrenheit.  
2. Find the mean, max, and min temperatures.  


In [6]:
temperatures = np.array([22, 24, 19, 21, 25, 23, 20])

# Convert to Fahrenheit: F = C * 9/5 + 32
fahrenheit = temperatures * 9/5 + 32
print("Fahrenheit:", fahrenheit)

# Statistics
print("Mean temp:", np.mean(temperatures))
print("Max temp:", np.max(temperatures))
print("Min temp:", np.min(temperatures))

Fahrenheit: [71.6 75.2 66.2 69.8 77.  73.4 68. ]
Mean temp: 22.0
Max temp: 25
Min temp: 19


---

<a id="pro-tips"></a>  
## 💡 **Pro Tips & Common Pitfalls**  

✅ **Always use `np.array()` instead of Python lists for numerical work.**  
❌ **Avoid mixing data types in NumPy arrays (they’ll get converted!).**  
🔥 **Use `np.zeros()`, `np.ones()`, and `np.arange()` for quick array creation.**  

```python
zeros = np.zeros(3)  # [0., 0., 0.]  
ones = np.ones(3)    # [1., 1., 1.]  
range_arr = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]  
```

---  

**Next Steps:**  
- Try the mini-project with your own data!  
- Explore NumPy’s documentation for more functions.  

**Keep coding!** 👨‍💻👩‍💻

# 🌟 Unleashing the Power of Numbers: An Introduction to NumPy\! 🌟

## Welcome, Data Explorer\! 🗺️

Greetings, fellow adventurer\! 👋 Are you ready to level up your Python skills and conquer the world of numerical computing? Then buckle up, because we're about to dive into NumPy – the secret superpower behind a vast amount of data science, machine learning, and scientific computing in Python\! This notebook will guide you through NumPy's wonders in a fun, interactive, and easy-to-understand way. Let's get started on this exciting quest\! 🚀

-----

## 📚 Table of Contents

1.  **Why NumPy? The Power-Up You Didn't Know You Needed\!** 💪

      * 1.1 What is NumPy?
      * 1.2 Python Lists vs. NumPy Arrays: A Speed Race\! 🏎️
      * 1.3 Installation (Just in Case\!)

2.  **Your First NumPy Array: Building Blocks of Data\!** 🧱

      * 2.1 Importing NumPy
      * 2.2 Creating Arrays from Python Lists
      * 2.3 Creating Arrays with Built-in Functions
      * 2.4 Quick Quiz: Array Architect\!

3.  **Array Attributes: Peeking Inside Your Data\!** 🕵️‍♀️

      * 3.1 `ndim`: Dimensions Demystified
      * 3.2 `shape`: The Array's Blueprint
      * 3.3 `size`: Counting All the Elements
      * 3.4 `dtype`: What Kind of Data?

4.  **Indexing and Slicing: Pinpointing Your Data\!** 📍

      * 4.1 1D Arrays: Just Like Lists\!
      * 4.2 2D Arrays: Rows and Columns
      * 4.3 Slicing: Grabbing Chunks of Data
      * 4.4 Boolean Indexing: Selecting with Conditions
      * 4.5 Challenge: Data Investigator\!

5.  **Array Operations: Math Made Easy\!** ➕➖✖️➗

      * 5.1 Element-wise Operations
      * 5.2 Matrix Multiplication (The Dot Product)
      * 5.3 Broadcasting: Smart Operations on Different Shapes 🧘‍♀️

6.  **Reshaping and Flattening: Changing Your Data's Form\!** 🔄

      * 6.1 `reshape()`: Rearranging Dimensions
      * 6.2 `flatten()` and `ravel()`: Making it Flat Again

7.  **Statistical Superpowers: Summarizing Your Data\!** 📊

      * 7.1 Mean, Median, and Standard Deviation
      * 7.2 Min and Max
      * 7.3 Summing Up\!

8.  **Random Number Generation: Simulating the World\!** 🎲

      * 8.1 `np.random.rand()`: Uniform Random Numbers
      * 8.2 `np.random.randint()`: Random Integers
      * 8.3 Shuffling and Choosing

9.  **Real-World Mini-Project: Analyzing Dummy Sensor Data** 🌡️📈

      * 9.1 Project Goal
      * 9.2 Step-by-Step Guide
      * 9.3 Your Turn: Expand the Analysis\!

10. **What's Next? Your NumPy Journey Continues\!** 🚀

      * 10.1 Resources for Further Learning
      * 10.2 Keep Practicing\!



-----

## 1\. Why NumPy? The Power-Up You Didn't Know You Needed\! 💪

### 1.1 What is NumPy?

NumPy, short for **Numerical Python**, is the fundamental package for numerical computation in Python. Think of it as Python's turbocharged engine for handling numbers, especially when you have lots and lots of them\! 🏎️ It provides a powerful array object, called `ndarray` (N-dimensional array), which is incredibly efficient for storing and performing operations on large datasets.

### 1.2 Python Lists vs. NumPy Arrays: A Speed Race\! 🏎️

You might be thinking, "But I already have Python lists for numbers, why do I need NumPy?" That's a great question\! While Python lists are versatile, they have a secret weakness when it comes to numerical operations on large datasets: **speed and memory efficiency**.

NumPy arrays are:

  * **Faster:** Operations on NumPy arrays are often implemented in C, making them significantly faster than equivalent operations on Python lists, especially for large datasets. This is because NumPy processes data without the overhead of Python's general-purpose objects.
  * **More Memory Efficient:** NumPy arrays store elements of the same data type contiguously in memory, unlike Python lists which can store elements of different types and therefore require more memory per element.

Let's see this in action with a quick speed test\! 🏁

```python
import numpy as np
import time

# Create a large Python list
python_list = list(range(1, 10000001)) # Numbers from 1 to 10 million

# Create a NumPy array
numpy_array = np.arange(1, 10000001) # Numbers from 1 to 10 million

# --- Speed Test: Adding 5 to each element ---

# Python List
start_time = time.time()
result_list = [x + 5 for x in python_list]
end_time = time.time()
print(f"Time taken by Python list: {end_time - start_time:.6f} seconds 🐢")

# NumPy Array
start_time = time.time()
result_array = numpy_array + 5
end_time = time.time()
print(f"Time taken by NumPy array: {end_time - start_time:.6f} seconds 🚀")
```

**Output (will vary slightly on your machine, but NumPy will be much faster):**

```
Time taken by Python list: 0.445230 seconds 🐢
Time taken by NumPy array: 0.007548 seconds 🚀
```

**Boom\!** 💥 You can see NumPy absolutely crushes Python lists in terms of speed for numerical operations. This efficiency is why NumPy is the backbone of so many scientific and data-intensive applications.

### 1.3 Installation (Just in Case\!) 🛠️

If you're using Jupyter Notebook (like you are now) or Google Colab, NumPy is usually pre-installed. Hooray\! 🎉

However, if you ever find yourself in a plain Python environment and need to install it, simply run this command in your terminal or command prompt:

```bash
pip install numpy
```

-----

## 2\. Your First NumPy Array: Building Blocks of Data\! 🧱

The core of NumPy is its `ndarray` object. It's a grid of values, all of the same type, indexed by a tuple of non-negative integers. Think of it like a super-organized spreadsheet or a stack of grids\!

### 2.1 Importing NumPy

The standard way to import NumPy is using the alias `np`. This makes your code cleaner and easier to read.

```python
import numpy as np
print("NumPy imported successfully! ✨")
```

**Output:**

```
NumPy imported successfully! ✨
```

### 2.2 Creating Arrays from Python Lists

The most common way to create a NumPy array is by converting a Python list (or a list of lists for multi-dimensional arrays) using `np.array()`.

#### 1D Array (Vector) 📏

```python
my_list = [1, 2, 3, 4, 5]
my_numpy_array = np.array(my_list)

print("My Python List:", my_list)
print("My NumPy Array:", my_numpy_array)
print("Type of my_numpy_array:", type(my_numpy_array))
```

**Output:**

```
My Python List: [1, 2, 3, 4, 5]
My NumPy Array: [1 2 3 4 5]
Type of my_numpy_array: <class 'numpy.ndarray'>
```

#### 2D Array (Matrix) 🔳

A 2D array is like a table with rows and columns. You can create it from a list of lists.

```python
my_list_of_lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_2d_array = np.array(my_list_of_lists)

print("My Python List of Lists:\n", my_list_of_lists)
print("\nMy 2D NumPy Array:\n", my_2d_array)
print("Type of my_2d_array:", type(my_2d_array))
```

**Output:**

```
My Python List of Lists:
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

My 2D NumPy Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Type of my_2d_array: <class 'numpy.ndarray'>
```

### 2.3 Creating Arrays with Built-in Functions 🏭

NumPy offers many convenient functions to create arrays quickly.

  * **`np.zeros()`:** Creates an array filled with zeros.
  * **`np.ones()`:** Creates an array filled with ones.
  * **`np.full()`:** Creates an array filled with a specific value.
  * **`np.arange()`:** Creates an array with a range of values (similar to Python's `range()`).
  * **`np.linspace()`:** Creates an array with evenly spaced numbers over a specified interval.
  * **`np.random.rand()` / `np.random.randint()`:** Creates arrays with random numbers (more on this later\!).

<!-- end list -->

```python
# Array of zeros (2 rows, 3 columns)
zeros_array = np.zeros((2, 3))
print("Array of Zeros:\n", zeros_array)

# Array of ones (3 rows, 2 columns)
ones_array = np.ones((3, 2))
print("\nArray of Ones:\n", ones_array)

# Array filled with a specific value (4x4, filled with 7)
full_array = np.full((4, 4), 7)
print("\nArray filled with 7:\n", full_array)

# Array with a range of values (0 to 9, step 1)
range_array = np.arange(10)
print("\nArray with range (0-9):\n", range_array)

# Array with a specific start, end (exclusive), and step
stepped_array = np.arange(2, 12, 2) # Start at 2, up to (but not including) 12, step by 2
print("\nArray with step (2, 4, 6, 8, 10):\n", stepped_array)

# Array with evenly spaced numbers (0 to 10, 5 elements)
linspace_array = np.linspace(0, 10, 5) # Start 0, end 10 (inclusive), 5 elements
print("\nArray with evenly spaced numbers (0-10, 5 elements):\n", linspace_array)
```

**Outputs:**

```
Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Array of Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with 7:
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]

Array with range (0-9):
 [0 1 2 3 4 5 6 7 8 9]

Array with step (2, 4, 6, 8, 10):
 [ 2  4  6  8 10]

Array with evenly spaced numbers (0-10, 5 elements):
 [ 0.   2.5  5.   7.5 10. ]
```

**💡 Pro Tip:** Notice how `np.zeros()` and `np.ones()` create arrays with `float` (decimal) numbers by default. If you need integers, you can specify `dtype=int` as an argument, like `np.zeros((2,3), dtype=int)`.

### 2.4 Quick Quiz: Array Architect\! 🏗️

Create the following NumPy arrays:

1.  A 1D array containing numbers from 10 to 15 (inclusive).
2.  A 2D array of size 3x3 filled entirely with the number 8.
3.  A 1D array of 4 evenly spaced numbers between 5 and 20 (inclusive).

<!-- end list -->

```python
# Your code here!
# 1. Array from 10 to 15
array_q1 = np.arange(10, 16) # Remember arange is exclusive of the stop value!
print("Quiz 1 Array:", array_q1)

# 2. 3x3 array of 8s
array_q2 = np.full((3, 3), 8)
print("\nQuiz 2 Array:\n", array_q2)

# 3. 4 evenly spaced numbers between 5 and 20
array_q3 = np.linspace(5, 20, 4)
print("\nQuiz 3 Array:", array_q3)
```

-----

## 3\. Array Attributes: Peeking Inside Your Data\! 🕵️‍♀️

Once you have a NumPy array, you can inspect its properties using various attributes. These attributes give you vital information about the array's structure and contents.

Let's use our `my_2d_array` from before:

```python
my_2d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Our 2D Array:\n", my_2d_array)
```

**Output:**

```
Our 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
```

### 3.1 `ndim`: Dimensions Demystified 📏

This attribute tells you the **number of dimensions (axes)** the array has.

  * A 1D array has `ndim = 1` (like a single row of numbers).
  * A 2D array has `ndim = 2` (like a table of rows and columns).
  * A 3D array has `ndim = 3` (like a stack of tables).

<!-- end list -->

```python
print("Number of dimensions (ndim):", my_2d_array.ndim)

my_1d_array = np.array([10, 20, 30])
print("Number of dimensions (ndim) for 1D array:", my_1d_array.ndim)
```

**Outputs:**

```
Number of dimensions (ndim): 2
Number of dimensions (ndim) for 1D array: 1
```

### 3.2 `shape`: The Array's Blueprint 🗺️

`shape` returns a tuple indicating the size of the array in each dimension. For a 2D array, it's `(rows, columns)`.

```python
print("Shape of the array (rows, columns):", my_2d_array.shape)

my_1d_array = np.array([10, 20, 30])
print("Shape of the 1D array:", my_1d_array.shape) # Notice it's (3,) - a tuple with one element
```

**Outputs:**

```
Shape of the array (rows, columns): (3, 3)
Shape of the 1D array: (3,)
```

### 3.3 `size`: Counting All the Elements 🔢

`size` returns the total number of elements in the array. It's simply the product of the elements in the `shape` tuple.

```python
print("Total number of elements (size):", my_2d_array.size)

my_big_array = np.zeros((5, 10)) # A 5x10 array
print("Total elements in a 5x10 array:", my_big_array.size)
```

**Outputs:**

```
Total number of elements (size): 9
Total elements in a 5x10 array: 50
```

### 3.4 `dtype`: What Kind of Data? 🧐

`dtype` (data type) tells you the type of data stored in the array's elements (e.g., `int64`, `float64`, `bool`). All elements in a NumPy array must have the same data type.

```python
print("Data type of elements (dtype):", my_2d_array.dtype)

float_array = np.array([1.0, 2.5, 3.7])
print("Data type of float array:", float_array.dtype)

bool_array = np.array([True, False, True])
print("Data type of boolean array:", bool_array.dtype)
```

**Outputs:**

```
Data type of elements (dtype): int64
Data type of float array: float64
Data type of boolean array: bool
```

**💡 Pro Tip:** If you create an array with mixed data types (e.g., integers and floats), NumPy will often "upcast" all elements to the more general type to avoid data loss. For example, `np.array([1, 2.5, 3])` will result in a `float64` array.

-----

## 4\. Indexing and Slicing: Pinpointing Your Data\! 📍

Accessing specific elements or portions of your array is super important. NumPy's indexing and slicing work similarly to Python lists, but with powerful extensions for multi-dimensional arrays.

Remember: Python (and NumPy) uses **0-based indexing**, meaning the first element is at index 0.

```python
# Let's create a 1D and a 2D array for our examples
arr_1d = np.arange(10, 16) # [10, 11, 12, 13, 14, 15]
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("1D Array:", arr_1d)
print("2D Array:\n", arr_2d)
```

**Outputs:**

```
1D Array: [10 11 12 13 14 15]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
```

### 4.1 1D Arrays: Just Like Lists\!

Access elements using square brackets `[]` and their index. Negative indices count from the end.

```python
print("First element of 1D array:", arr_1d[0])
print("Third element of 1D array:", arr_1d[2])
print("Last element of 1D array:", arr_1d[-1])
```

**Outputs:**

```
First element of 1D array: 10
Third element of 1D array: 12
Last element of 1D array: 15
```

### 4.2 2D Arrays: Rows and Columns 🧑‍🤝‍🧑

For 2D arrays, you use `[row_index, column_index]`. Think of it as coordinates\!

```python
# Accessing an element (row 0, column 1)
print("Element at (0, 1):", arr_2d[0, 1]) # This is the number 2

# Accessing an element (row 2, column 0)
print("Element at (2, 0):", arr_2d[2, 0]) # This is the number 7

# Accessing an entire row (all columns in row 1)
print("Second row (index 1):", arr_2d[1, :]) # The colon ":" means "all"

# Accessing an entire column (all rows in column 2)
print("Third column (index 2):", arr_2d[:, 2]) # The colon ":" means "all"
```

**Outputs:**

```
Element at (0, 1): 2
Element at (2, 0): 7
Second row (index 1): [4 5 6]
Third column (index 2): [3 6 9]
```

### 4.3 Slicing: Grabbing Chunks of Data 🍕

Slicing allows you to extract sub-arrays. The syntax is `[start:stop:step]`, where `stop` is **exclusive**.

#### 1D Array Slicing

```python
# Elements from index 1 up to (but not including) index 4
print("Elements from index 1 to 3:", arr_1d[1:4]) # [11, 12, 13]

# Elements from the beginning up to index 3
print("Elements up to index 3:", arr_1d[:3]) # [10, 11, 12]

# Elements from index 3 to the end
print("Elements from index 3 onwards:", arr_1d[3:]) # [13, 14, 15]

# Every second element
print("Every second element:", arr_1d[::2]) # [10, 12, 14]
```

**Outputs:**

```
Elements from index 1 to 3: [11 12 13]
Elements up to index 3: [10 11 12]
Elements from index 3 onwards: [13 14 15]
Every second element: [10 12 14]
```

#### 2D Array Slicing

You apply slicing to both dimensions, separated by a comma.

```python
# Get the sub-array from rows 0 and 1, and columns 0 and 1
# This will be:
# [[1, 2],
#  [4, 5]]
sub_array = arr_2d[0:2, 0:2]
print("Sub-array (rows 0-1, cols 0-1):\n", sub_array)

# Get all rows, and columns 1 and 2
# This will be:
# [[2, 3],
#  [5, 6],
#  [8, 9]]
sub_array_cols = arr_2d[:, 1:3]
print("\nSub-array (all rows, cols 1-2):\n", sub_array_cols)

# Get the second row and every second element from that row
print("\nSecond row, every second element:", arr_2d[1, ::2]) # This will be [4, 6]
```

**Outputs:**

```
Sub-array (rows 0-1, cols 0-1):
 [[1 2]
 [4 5]]

Sub-array (all rows, cols 1-2):
 [[2 3]
 [5 6]
 [8 9]]

Second row, every second element: [4 6]
```

**Common Pitfall:** When you slice a NumPy array, you often get a **view** of the original array, not a copy. This means if you modify the sliced array, the original array will also be modified\! If you want a true copy, use the `.copy()` method.

```python
original_array = np.array([10, 20, 30, 40, 50])
sliced_view = original_array[1:4] # View
sliced_copy = original_array[1:4].copy() # Copy

print("Original array:", original_array)
print("Sliced view:", sliced_view)
print("Sliced copy:", sliced_copy)

# Modify the view
sliced_view[0] = 99
print("\nAfter modifying sliced_view:")
print("Original array:", original_array) # Oh no! Original changed!
print("Sliced view:", sliced_view)

# Modify the copy
sliced_copy[0] = 100
print("\nAfter modifying sliced_copy:")
print("Original array:", original_array) # Original is safe!
print("Sliced copy:", sliced_copy)
```

**Outputs:**

```
Original array: [10 20 30 40 50]
Sliced view: [20 30 40]
Sliced copy: [20 30 40]

After modifying sliced_view:
Original array: [10 99 30 40 50]
Sliced view: [99 30 40]

After modifying sliced_copy:
Original array: [10 99 30 40 50]
Sliced copy: [100 30 40]
```

### 4.4 Boolean Indexing: Selecting with Conditions ✅

This is a super powerful feature\! You can use a boolean array (an array of `True`/`False` values) to select elements from another array. Wherever the boolean array has `True`, the corresponding element from the original array is selected.

```python
data = np.array([10, 25, 5, 40, 15, 30])

# Select elements greater than 20
condition = data > 20
print("Condition (data > 20):", condition)

selected_data = data[condition]
print("Selected data (greater than 20):", selected_data)

# Combined in one line:
print("Elements less than or equal to 15:", data[data <= 15])
```

**Outputs:**

```
Condition (data > 20): [False  True False  True False  True]
Selected data (greater than 20): [25 40 30]
Elements less than or equal to 15: [10  5 15]
```

### 4.5 Challenge: Data Investigator\! 🕵️‍♀️

You are given a 2D NumPy array representing daily temperatures (rows are days, columns are readings at different times).

```python
temperatures = np.array([
    [22, 25, 23, 26],
    [20, 23, 21, 24],
    [24, 27, 25, 28],
    [18, 20, 19, 21]
])
```

Perform the following tasks using indexing and slicing:

1.  Print the temperature reading for the **third day** (index 2) at the **second time slot** (index 1).
2.  Print all temperature readings for the **first day**.
3.  Print the temperature readings for **all days** at the **last time slot**.
4.  Print all temperatures that are **greater than 25**.

<!-- end list -->

```python
temperatures = np.array([
    [22, 25, 23, 26],
    [20, 23, 21, 24],
    [24, 27, 25, 28],
    [18, 20, 19, 21]
])

# 1. Temperature on third day, second time slot
print("1. Temp at (2, 1):", temperatures[2, 1])

# 2. All readings for the first day
print("\n2. All readings for first day:", temperatures[0, :])

# 3. All temperatures at the last time slot
print("\n3. All temps at last time slot:", temperatures[:, -1])

# 4. All temperatures greater than 25
print("\n4. Temps greater than 25:", temperatures[temperatures > 25])
```

-----

## 5\. Array Operations: Math Made Easy\! ➕➖✖️➗

One of the biggest advantages of NumPy is its ability to perform operations on entire arrays *element-wise* without needing explicit loops. This is called **vectorization** and is incredibly fast\!

```python
# Let's use these arrays for our operations
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

print("Array 1:", arr1)
print("Array 2:", arr2)
```

**Outputs:**

```
Array 1: [1 2 3 4]
Array 2: [5 6 7 8]
```

### 5.1 Element-wise Operations

You can perform basic arithmetic operations (`+`, `-`, `*`, `/`, `**`, `%`) directly on arrays. NumPy will apply the operation to corresponding elements.

```python
# Addition
print("Addition (arr1 + arr2):", arr1 + arr2)

# Subtraction
print("Subtraction (arr2 - arr1):", arr2 - arr1)

# Multiplication
print("Multiplication (arr1 * arr2):", arr1 * arr2) # NOT matrix multiplication!

# Division
print("Division (arr2 / arr1):", arr2 / arr1)

# Exponentiation
print("Exponentiation (arr1 ** 2):", arr1 ** 2)

# Modulus
print("Modulus (arr2 % arr1):", arr2 % arr1)

# You can also operate with a scalar (single number)
print("Add 10 to arr1:", arr1 + 10)
print("Multiply arr2 by 3:", arr2 * 3)
```

**Outputs:**

```
Addition (arr1 + arr2): [ 6  8 10 12]
Subtraction (arr2 - arr1): [4 4 4 4]
Multiplication (arr1 * arr2): [ 5 12 21 32]
Division (arr2 / arr1): [5.         3.         2.33333333 2.        ]
Exponentiation (arr1 ** 2): [ 1  4  9 16]
Modulus (arr2 % arr1): [0 0 1 0]
Add 10 to arr1: [11 12 13 14]
Multiply arr2 by 3: [15 18 21 24]
```

### 5.2 Matrix Multiplication (The Dot Product) 🔢

For true matrix multiplication, you use the `@` operator or `np.dot()`. This is crucial for linear algebra operations.

```python
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", matrix_a)
print("Matrix B:\n", matrix_b)

# Matrix multiplication using @ operator
result_matrix = matrix_a @ matrix_b
print("\nMatrix A @ Matrix B:\n", result_matrix)

# Matrix multiplication using np.dot()
result_dot = np.dot(matrix_a, matrix_b)
print("\nnp.dot(Matrix A, Matrix B):\n", result_dot)
```

**Outputs:**

```
Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]

Matrix A @ Matrix B:
 [[19 22]
 [43 50]]

np.dot(Matrix A, Matrix B):
 [[19 22]
 [43 50]]
```

### 5.3 Broadcasting: Smart Operations on Different Shapes 🧘‍♀️

Broadcasting is a powerful mechanism that allows NumPy to perform operations on arrays with different shapes. It's like NumPy intelligently "stretches" or "replicates" the smaller array to match the larger array's shape, without actually creating copies of the data. This makes operations very memory and computationally efficient.

**The Rules of Broadcasting (simplified):**

1.  **Dimensions are compared from right to left.**
2.  **Two dimensions are compatible if:**
      * They are equal.
      * One of them is 1.
3.  **If arrays have different numbers of dimensions, the smaller-dimensioned array is padded with ones on its left side.**

If these rules don't lead to a compatible shape, NumPy will raise a `ValueError`.

#### Example 1: Scalar to Array

A scalar (single number) is broadcast across the entire array.

```python
scalar = 10
array_1d = np.array([1, 2, 3])

result = array_1d + scalar
print(f"Array: {array_1d} + Scalar: {scalar} = {result}")
```

**Output:**

```
Array: [1 2 3] + Scalar: 10 = [11 12 13]
```

#### Example 2: 1D Array to 2D Array

```python
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
vector = np.array([10, 20, 30]) # Shape (3,)

# NumPy will broadcast 'vector' across each row of 'matrix'
result = matrix + vector
print("Matrix:\n", matrix)
print("\nVector:", vector)
print("\nMatrix + Vector (Broadcasted):\n", result)
```

**Explanation:** The `vector` (shape `(3,)`) is effectively stretched to match the `(3,3)` shape of the `matrix`. It's like `[10, 20, 30]` becomes `[[10, 20, 30], [10, 20, 30], [10, 20, 30]]` before addition, but without actually consuming that extra memory.

**Outputs:**

```
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Vector: [10 20 30]

Matrix + Vector (Broadcasted):
 [[11 22 33]
 [14 25 36]
 [17 28 39]]
```

#### Example 3: Different shaped 2D arrays

```python
matrix_a = np.array([[10, 20, 30]]) # Shape (1, 3)
matrix_b = np.array([[1, 2, 3],
                     [4, 5, 6]]) # Shape (2, 3)

# Compatible because the rightmost dimension (3) is equal,
# and the leftmost dimension (1) in matrix_a can be stretched to (2)
result = matrix_a + matrix_b
print("Matrix A (shape 1,3):\n", matrix_a)
print("\nMatrix B (shape 2,3):\n", matrix_b)
print("\nMatrix A + Matrix B (Broadcasted):\n", result)
```

**Outputs:**

```
Matrix A (shape 1,3):
 [[10 20 30]]

Matrix B (shape 2,3):
 [[1 2 3]
 [4 5 6]]

Matrix A + Matrix B (Broadcasted):
 [[11 22 33]
 [14 25 36]]
```

**Common Pitfall:** Broadcasting can be tricky. If shapes are incompatible, you'll get a `ValueError: operands could not be broadcast together with shapes ...`. Always check `array.shape` when you encounter such errors\!

-----

## 6\. Reshaping and Flattening: Changing Your Data's Form\! 🔄

Sometimes you have data in one shape, but you need it in another. NumPy provides powerful functions for this.

```python
# Let's start with a 1D array
my_array = np.arange(1, 13) # Numbers from 1 to 12
print("Original Array (1D):\n", my_array)
print("Shape:", my_array.shape)
```

**Outputs:**

```
Original Array (1D):
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)
```

### 6.1 `reshape()`: Rearranging Dimensions 📐

The `reshape()` method allows you to change the shape of an array without changing its data. The new shape must have the same total number of elements as the original array.

```python
# Reshape into a 3x4 matrix (3 rows, 4 columns)
reshaped_3x4 = my_array.reshape(3, 4)
print("\nReshaped to 3x4:\n", reshaped_3x4)
print("Shape:", reshaped_3x4.shape)

# Reshape into a 4x3 matrix (4 rows, 3 columns)
reshaped_4x3 = my_array.reshape(4, 3)
print("\nReshaped to 4x3:\n", reshaped_4x3)
print("Shape:", reshaped_4x3.shape)

# You can use -1 for one of the dimensions, and NumPy will figure it out!
# Reshape into 2 rows, let NumPy figure out columns
reshaped_2_auto = my_array.reshape(2, -1)
print("\nReshaped to 2 rows (auto columns):\n", reshaped_2_auto)
print("Shape:", reshaped_2_auto.shape)

# Reshape into auto rows, 6 columns
reshaped_auto_6 = my_array.reshape(-1, 6)
print("\nReshaped to auto rows (6 columns):\n", reshaped_auto_6)
print("Shape:", reshaped_auto_6.shape)

# Reshape into a 2x2x3 3D array
reshaped_3d = my_array.reshape(2, 2, 3)
print("\nReshaped to 2x2x3 (3D):\n", reshaped_3d)
print("Shape:", reshaped_3d.shape)
```

**Outputs:**

```
Reshaped to 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)

Reshaped to 4x3:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)

Reshaped to 2 rows (auto columns):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Shape: (2, 6)

Reshaped to auto rows (6 columns):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Shape: (2, 6)

Reshaped to 2x2x3 (3D):
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
```

**Common Pitfall:** If the new shape's total number of elements doesn't match the original array's `size`, `reshape()` will throw an error. E.g., `my_array.reshape(3, 5)` (15 elements) would fail on `my_array` (12 elements).

### 6.2 `flatten()` and `ravel()`: Making it Flat Again 📏

These methods convert a multi-dimensional array back into a 1D array.

  * **`flatten()`:** Always returns a **copy** of the array.
  * **`ravel()`:** Returns a **view** of the original array if possible, otherwise a copy. It's generally preferred for performance unless you specifically need a copy.

<!-- end list -->

```python
multi_dim_array = np.array([[1, 2, 3],
                            [4, 5, 6]])
print("Original Multi-dim Array:\n", multi_dim_array)

flattened_copy = multi_dim_array.flatten()
print("\nFlattened (copy):", flattened_copy)

raveled_view = multi_dim_array.ravel()
print("Raveled (view/copy):", raveled_view)

# Demonstrating copy vs view:
flattened_copy[0] = 999
print("\nAfter modifying flattened_copy:")
print("Original array:\n", multi_dim_array)
print("Flattened copy:", flattened_copy)

raveled_view[0] = 888
print("\nAfter modifying raveled_view:")
print("Original array:\n", multi_dim_array) # Original changed because ravel returned a view!
print("Raveled view:", raveled_view)
```

**Outputs:**

```
Original Multi-dim Array:
 [[1 2 3]
 [4 5 6]]

Flattened (copy): [1 2 3 4 5 6]
Raveled (view/copy): [1 2 3 4 5 6]

After modifying flattened_copy:
Original array:
 [[1 2 3]
 [4 5 6]]
Flattened copy: [999   2   3   4   5   6]

After modifying raveled_view:
Original array:
 [[888   2   3]
 [  4   5   6]]
Raveled view: [888   2   3   4   5   6]
```

-----

## 7\. Statistical Superpowers: Summarizing Your Data\! 📊

NumPy provides a wide range of functions for statistical analysis, making it incredibly easy to get insights from your numerical data.

```python
data_for_stats = np.array([10, 15, 20, 25, 30, 35, 40])
print("Data for statistics:", data_for_stats)

data_2d_for_stats = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("\n2D Data for statistics:\n", data_2d_for_stats)
```

**Outputs:**

```
Data for statistics: [10 15 20 25 30 35 40]

2D Data for statistics:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
```

### 7.1 Mean, Median, and Standard Deviation

  * **`np.mean()`:** The average value.
  * **`np.median()`:** The middle value when sorted.
  * **`np.std()`:** The standard deviation (how spread out the data is).

<!-- end list -->

```python
print("Mean of 1D data:", np.mean(data_for_stats))
print("Median of 1D data:", np.median(data_for_stats))
print("Standard Deviation of 1D data:", np.std(data_for_stats))

# For 2D arrays, you can calculate along an axis:
# axis=0 means along columns (for each column)
print("\nMean of 2D data (along columns - axis=0):", np.mean(data_2d_for_stats, axis=0))
# axis=1 means along rows (for each row)
print("Mean of 2D data (along rows - axis=1):", np.mean(data_2d_for_stats, axis=1))
```

**Outputs:**

```
Mean of 1D data: 25.0
Median of 1D data: 25.0
Standard Deviation of 1D data: 10.0

Mean of 2D data (along columns - axis=0): [4. 5. 6.]
Mean of 2D data (along rows - axis=1): [2. 5. 8.]
```

### 7.2 Min and Max

  * **`np.min()`:** The smallest value.
  * **`np.max()`:** The largest value.

<!-- end list -->

```python
print("Minimum of 1D data:", np.min(data_for_stats))
print("Maximum of 1D data:", np.max(data_for_stats))

# Also works along axes
print("\nMinimum of 2D data (along columns):", np.min(data_2d_for_stats, axis=0))
print("Maximum of 2D data (along rows):", np.max(data_2d_for_stats, axis=1))
```

**Outputs:**

```
Minimum of 1D data: 10
Maximum of 1D data: 40

Minimum of 2D data (along columns): [1 2 3]
Maximum of 2D data (along rows): [3 6 9]
```

### 7.3 Summing Up\!

  * **`np.sum()`:** Calculates the sum of all elements.

<!-- end list -->

```python
print("Sum of all elements in 1D data:", np.sum(data_for_stats))

# Summing along axes
print("\nSum of 2D data (all elements):", np.sum(data_2d_for_stats))
print("Sum of 2D data (along columns - axis=0):", np.sum(data_2d_for_stats, axis=0))
print("Sum of 2D data (along rows - axis=1):", np.sum(data_2d_for_stats, axis=1))
```

**Outputs:**

```
Sum of all elements in 1D data: 250

Sum of 2D data (all elements): 45
Sum of 2D data (along columns - axis=0): [12 15 18]
Sum of 2D data (along rows - axis=1): [ 6 15 24]
```

-----

## 8\. Random Number Generation: Simulating the World\! 🎲

NumPy's `random` module is incredibly useful for simulations, generating test data, and machine learning.

```python
# Always a good idea to set a "seed" for reproducibility
# If you run the code again with the same seed, you get the same "random" numbers.
np.random.seed(42) # The answer to everything! 😉
print("Random seed set to 42. Your random numbers should match mine! 👍")
```

**Output:**

```
Random seed set to 42. Your random numbers should match mine! 👍
```

### 8.1 `np.random.rand()`: Uniform Random Numbers

Generates random floats between 0 (inclusive) and 1 (exclusive) in a uniform distribution.

```python
# Single random float
print("Single random float:", np.random.rand())

# 1D array of 5 random floats
print("\n5 random floats (1D):", np.random.rand(5))

# 2D array (3x2) of random floats
print("\n3x2 random floats (2D):\n", np.random.rand(3, 2))
```

**Outputs (will be different each time if you don't set a seed, or if you run without `np.random.seed(42)` first):**

```
Single random float: 0.3745401188473625

5 random floats (1D): [0.95071431 0.73199394 0.59865848 0.15601864 0.15599452]

3x2 random floats (2D):
 [[0.05808361 0.86617615]
 [0.60111501 0.70807258]
 [0.02058449 0.96990985]]
```

### 8.2 `np.random.randint()`: Random Integers

Generates random integers within a specified range.

  * `low`: The lowest (inclusive) integer to be drawn.
  * `high`: The highest (exclusive) integer to be drawn.
  * `size`: The shape of the output array.

<!-- end list -->

```python
# Single random integer between 1 and 10 (inclusive)
print("Single random integer (1-10):", np.random.randint(1, 11))

# 1D array of 5 random integers between 0 and 100
print("\n5 random integers (0-100):", np.random.randint(0, 101, size=5))

# 2D array (2x3) of random integers between 50 and 100
print("\n2x3 random integers (50-100):\n", np.random.randint(50, 101, size=(2, 3)))
```

**Outputs (will be different without the seed or different seed):**

```
Single random integer (1-10): 7

5 random integers (0-100): [83 21 86 87 87]

2x3 random integers (50-100):
 [[74 65 52]
 [76 50 63]]
```

### 8.3 Shuffling and Choosing

  * **`np.random.shuffle()`:** Shuffles the contents of an array in place.
  * **`np.random.choice()`:** Randomly selects elements from an array.

<!-- end list -->

```python
my_numbers = np.array([1, 2, 3, 4, 5])
print("Original numbers:", my_numbers)

np.random.shuffle(my_numbers)
print("Shuffled numbers (in place):", my_numbers)

# Restore original for choice example
my_numbers = np.array([1, 2, 3, 4, 5])

# Choose 3 random elements (with replacement by default)
chosen_elements = np.random.choice(my_numbers, 3)
print("\nRandomly chosen 3 elements:", chosen_elements)

# Choose 3 random elements without replacement
chosen_unique = np.random.choice(my_numbers, 3, replace=False)
print("Randomly chosen 3 unique elements:", chosen_unique)
```

**Outputs (will vary):**

```
Original numbers: [1 2 3 4 5]
Shuffled numbers (in place): [5 1 3 4 2]

Randomly chosen 3 elements: [5 3 5]
Randomly chosen 3 unique elements: [4 1 2]
```

-----

## 9\. Real-World Mini-Project: Analyzing Dummy Sensor Data 🌡️📈

Let's apply what we've learned to a small, practical scenario\! Imagine you've collected temperature readings from a smart thermostat over a week, taken at different times of the day (morning, afternoon, evening, night).

### 9.1 Project Goal

Your goal is to:

1.  Create a NumPy array to store this data.
2.  Calculate daily average temperatures.
3.  Find the hottest and coldest readings of the week.
4.  Identify days where the *morning* temperature was above a certain threshold.

### 9.2 Step-by-Step Guide

```python
import numpy as np

# 1. Create a NumPy array for daily temperatures
# Assume 7 days (rows) and 4 readings per day (columns: morning, afternoon, evening, night)
# Let's use some realistic (dummy) temperature data in Celsius.
# Each row is a day, each column is a time slot.
weekly_temperatures = np.array([
    [18.5, 25.1, 22.0, 16.8],  # Day 1
    [17.9, 24.5, 21.5, 16.2],  # Day 2
    [19.0, 26.3, 23.1, 17.5],  # Day 3
    [17.2, 23.8, 20.9, 15.5],  # Day 4
    [20.1, 27.0, 24.5, 18.2],  # Day 5
    [19.5, 26.5, 23.8, 17.9],  # Day 6
    [18.8, 25.0, 22.5, 17.0]   # Day 7
])

print("Weekly Temperature Data:\n", weekly_temperatures)
print("\nShape of data:", weekly_temperatures.shape)

# 2. Calculate daily average temperatures
# We need the mean along each row (axis=1)
daily_averages = np.mean(weekly_temperatures, axis=1)
print("\nDaily Average Temperatures:\n", daily_averages)

# 3. Find the hottest and coldest readings of the week (overall)
hottest_reading = np.max(weekly_temperatures)
coldest_reading = np.min(weekly_temperatures)
print(f"\nHottest Reading of the Week: {hottest_reading}°C")
print(f"Coldest Reading of the Week: {coldest_reading}°C")

# 4. Identify days where the morning temperature was above a certain threshold (e.g., 18.0°C)
# Morning temperature is the first column (index 0)
morning_temps = weekly_temperatures[:, 0]
threshold = 18.0

days_above_threshold = morning_temps > threshold
print("\nDays where morning temp > 18.0°C (Boolean):", days_above_threshold)

# To get the actual morning temperatures for those days:
morning_temps_above_threshold = morning_temps[days_above_threshold]
print("Morning temperatures > 18.0°C:", morning_temps_above_threshold)

# To find out which specific days (using indices):
# np.where() can help here, it returns indices where the condition is True
day_indices = np.where(days_above_threshold)[0]
print("Indices of days where morning temp > 18.0°C:", day_indices)

# To print the actual day number (1-indexed for user-friendliness)
print("Days (1-indexed) where morning temp > 18.0°C:")
for day_idx in day_indices:
    print(f"  Day {day_idx + 1}: {morning_temps[day_idx]}°C")
```

**Outputs:**

```
Weekly Temperature Data:
 [[18.5 25.1 22.  16.8]
 [17.9 24.5 21.5 16.2]
 [19.  26.3 23.1 17.5]
 [17.2 23.8 20.9 15.5]
 [20.1 27.  24.5 18.2]
 [19.5 26.5 23.8 17.9]
 [18.8 25.  22.5 17. ]]

Shape of data: (7, 4)

Daily Average Temperatures:
 [20.6 20.025 21.475 19.35 22.45 21.925 20.825]

Hottest Reading of the Week: 27.0°C
Coldest Reading of the Week: 15.5°C

Days where morning temp > 18.0°C (Boolean): [ True False  True False  True  True  True]
Morning temperatures > 18.0°C: [18.5 19.  20.1 19.5 18.8]
Indices of days where morning temp > 18.0°C: [0 2 4 5 6]
Days (1-indexed) where morning temp > 18.0°C:
  Day 1: 18.5°C
  Day 3: 19.0°C
  Day 5: 20.1°C
  Day 6: 19.5°C
  Day 7: 18.8°C
```

### 9.3 Your Turn: Enhance the Analysis\! 💡

Now, it's your turn to be the data analyst\! Using the `weekly_temperatures` array, try to:

1.  Calculate the **average temperature for each time slot** across the entire week (e.g., average morning temp, average afternoon temp).
2.  Find out which day had the **highest daily average temperature**.
3.  Identify how many readings were **below 20°C**.

<!-- end list -->

```python
# Your code here!

# 1. Average temperature for each time slot (along columns, axis=0)
avg_time_slot_temps = np.mean(weekly_temperatures, axis=0)
print("1. Average temperature for each time slot (Morning, Afternoon, Evening, Night):\n", avg_time_slot_temps)

# 2. Day with the highest daily average temperature
# First, find the maximum daily average
max_avg_temp = np.max(daily_averages)
# Then, find the index of that maximum
day_with_max_avg_idx = np.argmax(daily_averages)
print(f"\n2. Day with highest daily average temp: Day {day_with_max_avg_idx + 1} ({max_avg_temp:.2f}°C)")

# 3. Count how many readings were below 20°C
readings_below_20 = weekly_temperatures[weekly_temperatures < 20]
count_below_20 = len(readings_below_20)
print(f"\n3. Number of readings below 20°C: {count_below_20}")
```

-----

## 10\. What's Next? Your NumPy Journey Continues\! 🚀

Congratulations\! You've successfully navigated the basics of NumPy and unlocked its power. You now have a solid foundation to handle numerical data efficiently in Python.

NumPy is a vast library, and this notebook just scratches the surface. Here are some areas you can explore next:

### 10.1 Resources for Further Learning

  * **Official NumPy Documentation:** The definitive source\! It's very comprehensive: [https://numpy.org/doc/stable/](https://numpy.org/doc/stable/)
  * **W3Schools NumPy Tutorial:** Great for quick refreshers and examples: [https://www.w3schools.com/python/numpy/default.asp](https://www.w3schools.com/python/numpy/default.asp)
  * **GeeksforGeeks NumPy Articles:** Many specific topics covered: [https://www.geeksforgeeks.org/python-numpy-tutorial/](https://www.geeksforgeeks.org/python-numpy-tutorial/)
  * **YouTube Tutorials:** Search for "NumPy tutorial for beginners" to find video walkthroughs.

### 10.2 Keep Practicing\! 💪

The best way to master any programming concept is to practice, practice, practice\!

  * **Solve coding challenges:** Websites like HackerRank, LeetCode, or Codewars have Python challenges where you can try to apply NumPy.
  * **Work on mini-projects:** Think of small data problems and try to solve them using NumPy.
  * **Explore other libraries:** NumPy is the foundation for many other powerful Python libraries for data science:
      * **Pandas:** For structured data manipulation (think spreadsheets).
      * **Matplotlib / Seaborn:** For data visualization.
      * **Scikit-learn:** For machine learning algorithms.
      * **SciPy:** For scientific and technical computing.

Remember, every expert was once a beginner. Keep experimenting, keep learning, and most importantly, keep having fun with Python and NumPy\! Happy coding\! 🎉✨

# 🚀 **Module 2: NumPy Arrays & Basic Operations**  
## 📚 **Table of Contents**  
1. [Creating Arrays 🏗️](#creating-arrays)  
   - `np.array()`  
   - `np.zeros()` & `np.ones()`  
   - `np.arange()`  
2. [Array Attributes 🔍](#array-attributes)  
   - `shape`, `dtype`, `ndim`  
3. [Indexing & Slicing ✂️](#indexing--slicing)  
4. [Reshaping & Transposing 🔄](#reshaping--transposing)  
5. [Quick Quiz ❓](#quick-quiz)  
6. [Mini-Project: Image Pixel Manipulation 🖼️](#mini-project)  
7. [Pro Tips & Common Pitfalls 💡](#pro-tips)  

---


<a id="creating-arrays"></a>  
## 1️⃣ **Creating Arrays 🏗️**  

### **1. `np.array()` - The Basic Constructor**  
Converts Python lists/tuples into NumPy arrays.

In [7]:
import numpy as np

# From a list
arr1 = np.array([1, 2, 3])  
print("1D Array:", arr1)  

# From nested lists (2D array)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  
print("\n2D Array:\n", arr2)

1D Array: [1 2 3]

2D Array:
 [[1 2 3]
 [4 5 6]]


### **2. `np.zeros()` & `np.ones()` - Pre-filled Arrays**  
Create arrays filled with `0`s or `1`s. 

In [8]:
zeros = np.zeros(3)          # 1D array of 0s  
ones_2d = np.ones((2, 3))    # 2x3 array of 1s  

print("Zeros:", zeros)  
print("\nOnes (2D):\n", ones_2d)

Zeros: [0. 0. 0.]

Ones (2D):
 [[1. 1. 1.]
 [1. 1. 1.]]


**💡 Pro Tip:** Use `np.empty()` for uninitialized arrays (faster but contains garbage values).  

### **3. `np.arange()` - Like Python’s `range()` but Better**  
Creates sequences with optional step sizes.  


In [9]:
seq1 = np.arange(5)          # 0 to 4  
seq2 = np.arange(1, 10, 2)   # 1 to 9, step=2  

print("0 to 4:", seq1)  
print("\nOdd numbers 1-9:", seq2)

0 to 4: [0 1 2 3 4]

Odd numbers 1-9: [1 3 5 7 9]


---

<a id="array-attributes"></a>  
## 2️⃣ **Array Attributes 🔍**  

| Attribute | Description | Example |  
|-----------|-------------|---------|  
| `shape`  | Dimensions of the array | `(3,)` for 1D, `(2,3)` for 2D |  
| `dtype`  | Data type of elements | `int64`, `float32` |  
| `ndim`   | Number of dimensions | `1` (vector), `2` (matrix) |  

**Example:**  

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)    # (2, 3)  
print("Data type:", arr.dtype) # int64 (default)  
print("Dimensions:", arr.ndim) # 2 

Shape: (2, 3)
Data type: int64
Dimensions: 2


**⚠️ Pitfall:** `shape` is a **tuple**, not a method (no parentheses needed!).  

---

<a id="indexing--slicing"></a>  
## 3️⃣ **Indexing & Slicing ✂️**  

### **1D Arrays (Like Python Lists)**

In [11]:
arr = np.array([10, 20, 30, 40, 50])

print("First element:", arr[0])       # 10  
print("Last element:", arr[-1])       # 50  
print("Sliced:", arr[1:4])            # [20, 30, 40]  

First element: 10
Last element: 50
Sliced: [20 30 40]


### **2D Arrays (Rows & Columns)** 

In [12]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("First row:", arr_2d[0])        # [1, 2, 3]  
print("Element at (2,1):", arr_2d[2, 1]) # 8 (3rd row, 2nd column)  
print("Column slicing:\n", arr_2d[:, 1]) # All rows, 2nd column → [2, 5, 8] 

First row: [1 2 3]
Element at (2,1): 8
Column slicing:
 [2 5 8]


**Key Syntax:**  
- `arr[row, column]`  
- `:` means "all" (e.g., `arr[:, 1]` = all rows, column 1).  

---

<a id="reshaping--transposing"></a>  
## 4️⃣ **Reshaping & Transposing 🔄**  

### **Reshaping (`reshape()`)**  
Change dimensions **without altering data**.

In [13]:
arr = np.arange(6)           # [0, 1, 2, 3, 4, 5]  
reshaped = arr.reshape(2, 3)  # 2x3 matrix  

print("Original shape:", arr.shape)  
print("Reshaped:\n", reshaped)

Original shape: (6,)
Reshaped:
 [[0 1 2]
 [3 4 5]]


**⚠️ Pitfall:** Total elements must match! `(6,)` → `(2,3)` works, but `(2,4)` fails.  

### **Transposing (`T` or `transpose()`)**  
Swap rows and columns. 

In [14]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])  
print("Original:\n", matrix)  
print("\nTransposed:\n", matrix.T) 

Original:
 [[1 2]
 [3 4]
 [5 6]]

Transposed:
 [[1 3 5]
 [2 4 6]]


---

<a id="quick-quiz"></a>  
## ❓ **Quick Quiz**  

1. **What does `arr.shape` return for a 3x4 array?**  
   - A) `(3)`  
   - B) `(3, 4)` ✅  
   - C) `12`  

2. **How do you get every other element in a 1D array?**  
   - A) `arr[::2]` ✅  
   - B) `arr[0:2]`  
   - C) `arr[:, 2]`  

---

<a id="mini-project"></a>  
## 🎯 **Mini-Project: Image Pixel Manipulation 🖼️**  

**Scenario:** A grayscale image is a 2D NumPy array (0=black, 255=white).  

**Tasks:**  
1. Flip the image vertically.  
2. Extract the top-left 2x2 corner.  


In [15]:
image = np.array([
    [50, 100, 150],  
    [200, 255, 30],  
    [80, 40, 10]  
])

# Flip vertically (reverse rows)
flipped = image[::-1, :]  
print("Flipped:\n", flipped)  

# Top-left 2x2 corner
corner = image[:2, :2]  
print("\nCorner:\n", corner) 

Flipped:
 [[ 80  40  10]
 [200 255  30]
 [ 50 100 150]]

Corner:
 [[ 50 100]
 [200 255]]


---

<a id="pro-tips"></a>  
## 💡 **Pro Tips & Common Pitfalls**  

✅ **Use `arr.copy()` to avoid modifying the original array accidentally.**  
❌ **Avoid `arr = arr.reshape()` (use `arr.reshape()` directly or reassign).**  
🔥 **`np.linspace()` is great for creating evenly spaced ranges (e.g., for plots).**  

```python
linear_range = np.linspace(0, 1, 5)  # [0., 0.25, 0.5, 0.75, 1.]  
```

---

## 🎉 **Key Takeaways**  
✔ Create arrays with `np.array()`, `np.zeros()`, `np.arange()`.  
✔ Inspect `shape`, `dtype`, and `ndim` to understand array structure.  
✔ Slice arrays with `arr[row, col]` and `:` for ranges.  
✔ Reshape/transpose to manipulate dimensions.  

**Next Steps:**  
- Try reshaping a 1D array into a 3D tensor!  
- Explore NumPy’s random module (`np.random.rand()`).  

**Happy coding!** 👨‍💻👩‍💻

# 🚀 **Module 3: Array Operations & Broadcasting**  

## 📚 **Table of Contents**  
1. [Vectorized Operations ➕](#vectorized-operations)  
   - Element-wise Math  
   - Comparison Operations  
2. [Aggregation Functions 📊](#aggregation-functions)  
   - `sum()`, `mean()`, `max()`, `min()`  
   - Axis Argument  
3. [Broadcasting Rules 📡](#broadcasting-rules)  
   - Rules Explained  
   - Practical Examples  
4. [Quick Quiz ❓](#quick-quiz)  
5. [Mini-Project: Student Grade Analysis 📚](#mini-project)  
6. [Pro Tips & Common Pitfalls 💡](#pro-tips)  

---

<a id="vectorized-operations"></a>  
## 1️⃣ **Vectorized Operations ➕**  

### **Element-wise Math**  
NumPy performs operations on entire arrays **without loops**!  


In [16]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)          # [5 7 9]  
print("Multiplication:", a * b)    # [4 10 18]  
print("Exponents:", a ** 2)        # [1 4 9]  
print("Sin:", np.sin(a))           # [0.8415, 0.9093, 0.1411]  

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Exponents: [1 4 9]
Sin: [0.84147098 0.90929743 0.14112001]


**Key Idea:**  
- Operations are applied to **each element** individually.  
- Works for `+`, `-`, `*`, `/`, `**`, and most math functions (`np.sin`, `np.log`, etc.).  

### **Comparison Operations**  
Get **Boolean arrays** from element-wise comparisons.  


In [17]:
temps = np.array([22, 25, 19, 30, 15])
print("Hot days:", temps > 25)  # [False False False  True False]  
print("Mean temp:", temps.mean())  # 22.2 

Hot days: [False False False  True False]
Mean temp: 22.2


---

<a id="aggregation-functions"></a>  
## 2️⃣ **Aggregation Functions 📊**  

Compute statistics over entire arrays or specific axes.  

### **Basic Aggregations**  

In [18]:
data = np.array([[1, 2], [3, 4]])

print("Total sum:", np.sum(data))       # 10  
print("Column sums:", np.sum(data, axis=0))  # [4 6] (sum columns)  
print("Row means:", np.mean(data, axis=1))  # [1.5 3.5] (mean of each row)  

Total sum: 10
Column sums: [4 6]
Row means: [1.5 3.5]


| Function | Description |  
|----------|-------------|  
| `sum()` | Sum of elements |  
| `mean()` | Average |  
| `max()`/`min()` | Maximum/minimum value |  
| `std()` | Standard deviation |  

**Axis Guide:**  
- `axis=0`: Operate **down columns** (for 2D: row → column)  
- `axis=1`: Operate **across rows** (for 2D: column → row)  

**Example:**  

In [19]:
sales = np.array([[100, 200], [150, 50]])
print("Max per column:", sales.max(axis=0))  # [150 200] 

Max per column: [150 200]


---

<a id="broadcasting-rules"></a>  
## 3️⃣ **Broadcasting Rules 📡**  

NumPy’s trick to **make arrays of different shapes compatible**!  

### **Rules Simplified**  
1. **Align shapes from the right.**  
2. **Dimensions must match or be 1.**  
3. **Missing dimensions are treated as 1.**  

**Example 1: Scalar + Array** 

In [20]:
arr = np.array([1, 2, 3])
print(arr + 5)  # [6 7 8] (5 is "stretched" to [5, 5, 5])  

[6 7 8]


**Example 2: Different Shapes**  

In [21]:
a = np.array([[1], [2], [3]])  # Shape (3, 1)  
b = np.array([10, 20, 30])      # Shape (3,) → (1, 3)  
print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


**How?**  
- `a` is (3,1), `b` is (3,) → reshaped to (1,3).  
- Both are "stretched" to (3,3) for operation.  

**⚠️ Pitfall:** Broadcasting fails if shapes can’t align!

In [22]:
a = np.array([1, 2, 3])
b = np.array([10, 20])
try:
    print(a + b)  # ❌ Error: shapes (3,) and (2,) mismatch!
except ValueError as e:
    print("Error:", e)

Error: operands could not be broadcast together with shapes (3,) (2,) 


---

<a id="quick-quiz"></a>  
## ❓ **Quick Quiz**  

1. **What’s the output of `np.array([1, 2, 3]) * 2`?**  
   - A) `[1, 2, 3, 1, 2, 3]`  
   - B) `[2, 4, 6]` ✅  
   - C) `[1, 4, 9]`  

2. **Which axis would you use to sum columns in a 2D array?**  
   - A) `axis=0` ✅  
   - B) `axis=1`  
   - C) `axis=-1`

---

<a id="mini-project"></a>  
## 🎯 **Mini-Project: Student Grade Analysis 📚**  

**Scenario:** Calculate statistics for student grades across 3 subjects.

In [23]:
grades = np.array([
    [85, 90, 78],  # Student 1  
    [92, 88, 95],   # Student 2  
    [75, 80, 82]    # Student 3  
])

# Task 1: Average grade per student (row means)
avg_grades = np.mean(grades, axis=1)
print("Average per student:", avg_grades)  # [84.33, 91.67, 79.0]  

# Task 2: Highest grade in each subject (column max)
max_subject = grades.max(axis=0)
print("Highest per subject:", max_subject)  # [92, 90, 95]  

# Task 3: Normalize grades (divide by max possible = 100)
normalized = grades / 100
print("\nNormalized:\n", normalized)

Average per student: [84.33333333 91.66666667 79.        ]
Highest per subject: [92 90 95]

Normalized:
 [[0.85 0.9  0.78]
 [0.92 0.88 0.95]
 [0.75 0.8  0.82]]




---

<a id="pro-tips"></a>  
## 💡 **Pro Tips & Common Pitfalls**  

✅ **Use `keepdims=True` to preserve dimensions in aggregations (e.g., `sum(axis=1, keepdims=True)`).**  
❌ **Avoid `axis=-1` unless you’re sure about the array’s dimensions (it refers to the last axis).**  
🔥 **Combine broadcasting with aggregation for powerful computations:**  

```python
# Subtract row means to center data
centered = grades - grades.mean(axis=1, keepdims=True)  
```

---

## 🎉 **Key Takeaways**  
✔ **Vectorized ops** are fast and loop-free.  
✔ **Aggregations** (`sum`, `mean`, etc.) work on entire arrays or axes.  
✔ **Broadcasting** lets you mix shapes intelligently.  

**Next Steps:**  
- Try multiplying a 3x1 matrix by a 1x3 matrix using broadcasting!  
- Explore logical aggregations (`np.all`, `np.any`).  

# 🚀 **Module 4: Advanced NumPy Techniques**  

## 📚 **Table of Contents**  
1. [Boolean Masking & Fancy Indexing 🎭](#boolean-masking--fancy-indexing)  
   - Conditional Selection  
   - Indexing with Arrays  
2. [Random Number Generation 🎲](#random-number-generation)  
   - `np.random` Basics  
   - Distributions (Uniform, Normal)  
3. [Linear Algebra Basics 📐](#linear-algebra-basics)  
   - `np.dot()` & Matrix Multiplication  
   - `np.linalg.inv()` & Inverses  
4. [Quick Quiz ❓](#quick-quiz)  
5. [Hands-on Project: Stock Price Analysis 📈](#hands-on-project)  
6. [Pro Tips & Common Pitfalls 💡](#pro-tips)  

---

<a id="boolean-masking--fancy-indexing"></a>  
## 1️⃣ **Boolean Masking & Fancy Indexing 🎭**  

### **Boolean Masking (Conditional Selection)**  
Select elements based on conditions.  


In [24]:
import numpy as np

prices = np.array([120, 95, 150, 80, 200])
mask = prices > 100
print("Mask:", mask)  # [True, False, True, False, True]  
print("High prices:", prices[mask])  # [120, 150, 200]  

# Multiple conditions
mask = (prices > 90) & (prices < 160)  # AND operation  
print("Mid-range prices:", prices[mask])  # [120, 95, 150] 

Mask: [ True False  True False  True]
High prices: [120 150 200]
Mid-range prices: [120  95 150]


**Key Idea:**  
- Create a **Boolean array** (`True`/`False`) from conditions.  
- Use it to **filter** the original array.  

### **Fancy Indexing (Indexing with Arrays)**  
Select elements using integer arrays.

In [25]:
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([0, 2, 4])  # Pick 1st, 3rd, 5th elements  
print("Selected:", arr[indices])  # [10, 30, 50]  

# 2D Example
matrix = np.array([[1, 2], [3, 4], [5, 6]])
row_indices = np.array([0, 2])
col_indices = np.array([1, 0])
print("Custom selections:", matrix[row_indices, col_indices])  # [2, 5]

Selected: [10 30 50]
Custom selections: [2 5]


---

<a id="random-number-generation"></a>  
## 2️⃣ **Random Number Generation 🎲**  

### **Basics with `np.random`**  
Generate random numbers from different distributions.  


In [26]:
# Uniform distribution (0 to 1)
uniform = np.random.rand(3)  # [0.42, 0.15, 0.89]  

# Integers (low, high, size)
dice_rolls = np.random.randint(1, 7, size=5)  # [4, 2, 6, 1, 3]  

# Normal distribution (mean=0, std=1)
normal = np.random.randn(3)  # [-0.3, 1.2, -0.7]  

print("Uniform:", uniform)
print("Dice rolls:", dice_rolls)
print("Normal:", normal)

Uniform: [0.59013982 0.22854728 0.42022402]
Dice rolls: [2 2 1 3 2]
Normal: [-0.68964114 -2.14190161  0.39746973]


**Common Functions:**  
| Function | Description |  
|----------|-------------|  
| `rand()` | Uniform (0, 1) |  
| `randint()` | Random integers |  
| `randn()` | Standard normal |  
| `normal()` | Custom normal (mean, std) |  

### **Seeding for Reproducibility**  
Fix the random state for consistent results.  


In [ ]:
np.random.seed(42)  # Magic number for reproducibility  
print("Fixed rand:", np.random.rand(2))  # Always [0.37, 0.95]  

---

<a id="linear-algebra-basics"></a>  
## 3️⃣ **Linear Algebra Basics 📐**  

### **Matrix Multiplication (`np.dot()` or `@`)**  
Multiply matrices (not element-wise!).  


In [27]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Method 1
dot_product = np.dot(A, B)  
# Method 2 (Python 3.5+)
at_symbol = A @ B  

print("Dot product:\n", dot_product)
print("@ operator:\n", at_symbol)

Dot product:
 [[19 22]
 [43 50]]
@ operator:
 [[19 22]
 [43 50]]


**Formula:**  
Row 1 × Column 1: `(1*5 + 2*7) = 19`  

### **Matrix Inversion (`np.linalg.inv()`)**  
Find the inverse of a square matrix.  


In [28]:
matrix = np.array([[1, 2], [3, 4]])
inverse = np.linalg.inv(matrix)  

print("Inverse:\n", inverse)  
print("Verify (A × A⁻¹ = I):\n", matrix @ inverse)  # ≈ Identity matrix  

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Verify (A × A⁻¹ = I):
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


**⚠️ Pitfall:** Not all matrices are invertible (singular matrices raise errors).  

---

<a id="quick-quiz"></a>  
## ❓ **Quick Quiz**  

1. **How to select elements >50 from an array `arr`?**  
   - A) `arr[arr > 50]` ✅  
   - B) `arr > 50`  
   - C) `arr.select(50)`  

2. **What does `np.random.seed(42)` do?**  
   - A) Generates 42 random numbers  
   - B) Ensures reproducible random numbers ✅  
   - C) Creates a 42×42 matrix  


---

<a id="hands-on-project"></a>  
## 🎯 **Hands-on Project: Stock Price Analysis 📈**  

**Scenario:** Analyze a week of stock prices (in USD).  


In [29]:
# Simulated stock prices (Mon-Fri)
prices = np.array([145.3, 148.1, 142.5, 150.2, 147.8])

# Task 1: Daily returns (% change)
daily_returns = (prices[1:] - prices[:-1]) / prices[:-1] * 100  
print("Daily returns (%):", np.round(daily_returns, 2))  

# Task 2: Volatility (std of returns)
volatility = np.std(daily_returns)  
print("Volatility:", np.round(volatility, 2), "%")  

# Task 3: Mask for positive returns
positive_days = prices[1:][daily_returns > 0]  
print("Days with gains:", positive_days)  

# Task 4: Correlation matrix (if multiple stocks)
stock_A = np.array([145, 148, 142, 150, 148])  
stock_B = np.array([320, 325, 318, 322, 319])  
correlation = np.corrcoef(stock_A, stock_B)[0, 1]  
print("\nCorrelation (A vs B):", np.round(correlation, 2))

Daily returns (%): [ 1.93 -3.78  5.4  -1.6 ]
Volatility: 3.49 %
Days with gains: [148.1 150.2]

Correlation (A vs B): 0.62



---

<a id="pro-tips"></a>  
## 💡 **Pro Tips & Common Pitfalls**  

✅ **Use `np.where()` for conditional replacements:**  
```python
arr = np.array([1, -2, 3, -4])
cleaned = np.where(arr < 0, 0, arr)  # Replace negatives with 0  
```  

❌ **Avoid `np.matrix` (deprecated; use `np.array` for linear algebra).**  

🔥 **Eigenvalues/vectors (advanced):**  
```python
eigenvalues, eigenvectors = np.linalg.eig([[1, 2], [2, 1]])  
```

---

## 🎉 **Key Takeaways**  
✔ **Boolean masking** filters data conditionally.  
✔ **Fancy indexing** selects elements using arrays.  
✔ **`np.random`** generates random numbers (control with seeds).  
✔ **Linear algebra** (`dot`, `inv`) powers ML/data science.  

**Next Steps:**  
- Try solving a system of equations with `np.linalg.solve()`.  
- Simulate a random walk using `np.cumsum()` on random steps.  

**Happy analyzing!** 👨‍💻👩‍💻